// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// ConfigurationListerExpansion allows custom methods to be added to
// ConfigurationLister.
type ConfigurationListerExpansion interface{}

// ConfigurationNamespaceListerExpansion allows custom methods to be added to
// ConfigurationNamespaceLister.
type ConfigurationNamespaceListerExpansion interface{}
