// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
	v1alpha1 "github.com/lvs-nginx-controller/pkg/client/clientset/versioned/typed/controller/v1alpha1"
)


type FakeLvs-nginx-controllerV1alpha1 struct {
	*testing.Fake
}

func (c *FakeLvs-nginx-controllerV1alpha1) Configurations(namespace string) v1alpha1.ConfigurationInterface {
	return &FakeConfigurations{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeLvs-nginx-controllerV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
